spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dpdb
    username: root
    password: lion
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8084
  error:
    include-message: always
